feature/PEER-191-1: Email notifications
peeranha/peeranha-web pull request #1393
Opened 2023-03-15 08:57 UTC by alexeishulga

2023-03-15 13:34 UTC, AweAwe95 commented on app/containers/ChangeEmail/ConfirmEmailForm.jsx
> +          }
declare a separate function

2023-03-16 19:57 UTC, almondy22 requested changes

2023-03-16 19:57 UTC, almondy22 commented on app/components/ToogleSwitch/ToggleSwitch.tsx
> +  const onToggle = () => setIsToggled(!isToggled);
Wrap this handler in `useCallback`

2023-03-16 19:57 UTC, almondy22 commented on app/containers/ChangeEmail/ConfirmEmailForm.jsx
> +  const [encorrectCode, setEncorrectCode] = useState(verificationCodeError);
Typo, change to `incorrect`

2023-03-16 19:57 UTC, almondy22 commented on app/containers/ChangeEmail/ConfirmEmailForm.jsx
> +            setEncorrectCode(verificationCode !== e.target.value ? false : true)
Just `setIncorrectCode(verificationCode === e.target.value)`

2023-03-16 19:57 UTC, almondy22 commented on app/containers/ChangeEmail/index.js
> +          onClick={(e) => setEmailAddress(e.target.form[0].value)}
Make separate handler function and wrap it in `useCallback`

2023-03-16 19:57 UTC, almondy22 commented on app/containers/ChangeEmail/index.js
> +          onClick={(e) => setEmailAddress(e.target.form[0].value)}
Also look for other places where you have same thing and fix it

2023-03-24 11:43 UTC, closed without merging