feature/PEER-968: Add clicable link to the footer
peeranha/peeranha-web pull request #1413
Opened 2023-03-21 12:09 UTC by alexeishulga

2023-03-21 14:53 UTC, AweAwe95 requested changes

2023-03-21 14:53 UTC, AweAwe95 commented on app/containers/Footer/Footer.tsx
> +const stylesSingle = singleCommunityStyles();
communityStyles

2023-03-21 14:56 UTC, AweAwe95 approved these changes

2023-03-22 10:15 UTC, almondy22 approved these changes

2023-03-23 10:12 UTC, YuriyLu approved these changes

2023-03-27 10:24 UTC, merged