Feature/peer 469 1
peeranha/peeranha-web pull request #1416
Opened 2023-03-23 11:51 UTC by YuriyLu

2023-03-24 09:07 UTC, alexeishulga commented on app/containers/App/routes.ts
> +} from '../../utils/properties';
use `from 'utils/properties';`

2023-03-27 11:16 UTC, alexeishulga approved these changes

2023-03-27 14:39 UTC, almondy22 requested changes

2023-03-27 14:39 UTC, almondy22 commented on app/containers/ChangeLocale/ChangeLocaleButton.tsx
> +      }
What is this?
Use
onClick={() => setOpen?.(true)}
or
onClick={() => setOpen && setOpen(true)}

2023-05-12 10:54 UTC, closed without merging