feature/PEER-950-1: Roll back old dropdowns
peeranha/peeranha-web pull request #1418
Opened 2023-03-24 09:57 UTC by alexeishulga

2023-03-24 11:51 UTC, almondy22 requested changes

2023-03-24 11:51 UTC, almondy22 commented on app/components/FormFields/TranslationsField.tsx
> +        dataAttribute={'dropdownMenu'}
```suggestion
        dataAttribute="dropdownMenu"
```

2023-03-24 12:00 UTC, alexeishulga commented on app/components/FormFields/TranslationsField.tsx
> +        dataAttribute={'dropdownMenu'}
done: https://github.com/peeranha/peeranha-web/pull/1418/commits/e2b0183a14780e4f3b0a4d58cfe79cfaaf8e9c9b

2023-03-27 08:28 UTC, alexeishulga commented on app/components/FormFields/TranslationsField.tsx
> +        id="translationsField_dropdown_id"
yes, this is a required prop

2023-03-27 08:32 UTC, AweAwe95 approved these changes

2023-03-27 14:43 UTC, almondy22 approved these changes

2023-03-29 11:38 UTC, merged