PEER-335 Add information about IPFS hash to each post answer and comment
peeranha/peeranha-web pull request #737
Opened 2022-04-19 05:13 UTC by andreilarin

2022-04-20 03:05 UTC, sergeyi23 commented
Please use another icon attached to JIRA ticket:
<img width="36" alt="image" src="https://user-images.githubusercontent.com/8031821/164142098-09b7fd6a-58bf-4dc7-8461-d7c129de4cc1.png">

2022-04-20 03:05 UTC, sergeyi23 commented
Use IPFS icon inside the popup

2022-04-20 03:07 UTC, sergeyi23 commented
Fix conflicts

2022-04-20 03:08 UTC, sergeyi23 commented
FYI. I replaced the blockchain icon with another that has thinner lines.

2022-04-20 21:41 UTC, sergeyi23 commented
Not able to open any of the quesiton pages:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/8031821/164327627-f8bcaae7-fb8d-4012-ba60-80331af3f8db.png">

2022-04-26 22:59 UTC, sergeyi23 commented
I see error again:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/8031821/165406325-477f95a9-3e7a-4f59-95c2-b10f417900c4.png">

2022-04-26 23:00 UTC, sergeyi23 requested changes
The app is crashing again when open the page.
Why does this happen?

2022-04-27 11:50 UTC, Lampardks commented on app/containers/Questions/Content/Body/IPFSInformation.js
> +export default memo(IPFSInformation);
у тебя простой компонент, где нет сложной логики, тут не нужно использовать memo

чрезмерное использование memo ведет к переоптимизации приложения

2022-04-27 11:50 UTC, Lampardks commented on app/containers/ViewQuestion/ContentHeader.jsx
> +              <FormattedMessage {...commonMessages.source} />
такая передача параметров плохая практика, допускается такой вариант, когда ты уверен, что тебе все параметры понадобятся в компоненте FormattedMessage

собственно вопрос, тебе все параметры из переменной commonMessages.source нужны в компоненте FormattedMessage?

2022-04-27 12:01 UTC, andreilarin commented on app/containers/Questions/Content/Body/IPFSInformation.js
> +export default memo(IPFSInformation);
исправлено

2022-04-27 12:01 UTC, andreilarin commented on app/containers/ViewQuestion/ContentHeader.jsx
> +              <FormattedMessage {...commonMessages.source} />
нет, не все, я делал как в примерах в этом же коде выше, но без rest оператора выскакивает синтаксическая ошибка

2022-04-27 12:45 UTC, Lampardks commented on app/containers/ViewQuestion/ContentHeader.jsx
> +              <FormattedMessage {...commonMessages.source} />
какая именно ошибка?
сколько параметров тебе нужно в FormattedMessage?

2022-04-27 12:58 UTC, andreilarin commented on app/containers/ViewQuestion/ContentHeader.jsx
> +              <FormattedMessage {...commonMessages.source} />
SyntaxError:  Unexpected token, expected "..."

2022-04-28 05:01 UTC, sergeyi23 commented
Icon color has to match other icons:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/8031821/165679802-e20a0226-20e5-4c04-a602-de6f20f74d8a.png">

2022-04-29 02:28 UTC, sergeyi23 approved these changes

2022-04-29 02:29 UTC, merged